apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
# authorization/authentication
authentication:
  anonymous:
    enabled: false
  webhook:
    enabled: true
  x509:
    clientCAFile: /etc/kubernetes/pki/ca.crt
authorization:
  mode: Webhook
# cgroup configuration
cgroupDriver: systemd
# DNS configuration
clusterDNS:
- 10.32.0.10
resolvConf: /etc/resolv.conf
clusterDomain: cluster.local
# health checking
healthzBindAddress: 127.0.0.1
healthzPort: 10248
# logs?
logging: {}
# static pod manifests
staticPodPath: /etc/kubernetes/manifests
# tls stuff
tlsCertFile: /etc/kubernetes/pki/kubelet-server.crt
tlsPrivateKeyFile: /etc/kubernetes/pki/kubelet-server.key
